"""empty message

Revision ID: 9a3d25164202
Revises: cd1736057386
Create Date: 2023-09-15 10:47:08.428050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3d25164202'
down_revision = 'cd1736057386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('terrain')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    # ### end Alembic commands ###
